packages:
  - "packages/*"
  - "apps/*"
allowBuilds:
  core-js-pure: false
  esbuild: true
  sharp: true
  workerd: true
minimumReleaseAgeExclude:
  - '@cloudflare/workers-types@4.20260527.1'
  - '@dnd-kit/abstract@0.5.0'
  - '@dnd-kit/collision@0.5.0'
  - '@dnd-kit/dom@0.5.0'
  - '@dnd-kit/geometry@0.5.0'
  - '@dnd-kit/react@0.5.0'
  - '@dnd-kit/state@0.5.0'
