/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellIndexRouteImport } from './routes/_shell.index'
import { Route as ShellSettingsRouteImport } from './routes/_shell.settings'
import { Route as ShellSavedRouteImport } from './routes/_shell.saved'
import { Route as ShellFoldersFolderIdRouteImport } from './routes/_shell.folders.$folderId'
import { Route as ShellFeedsFeedIdRouteImport } from './routes/_shell.feeds.$feedId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsRoute = ShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSavedRoute = ShellSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => ShellRoute,
} as any)
const ShellFoldersFolderIdRoute = ShellFoldersFolderIdRouteImport.update({
  id: '/folders/$folderId',
  path: '/folders/$folderId',
  getParentRoute: () => ShellRoute,
} as any)
const ShellFeedsFeedIdRoute = ShellFeedsFeedIdRouteImport.update({
  id: '/feeds/$feedId',
  path: '/feeds/$feedId',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/login': typeof LoginRoute
  '/saved': typeof ShellSavedRoute
  '/settings': typeof ShellSettingsRoute
  '/feeds/$feedId': typeof ShellFeedsFeedIdRoute
  '/folders/$folderId': typeof ShellFoldersFolderIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/saved': typeof ShellSavedRoute
  '/settings': typeof ShellSettingsRoute
  '/': typeof ShellIndexRoute
  '/feeds/$feedId': typeof ShellFeedsFeedIdRoute
  '/folders/$folderId': typeof ShellFoldersFolderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/login': typeof LoginRoute
  '/_shell/saved': typeof ShellSavedRoute
  '/_shell/settings': typeof ShellSettingsRoute
  '/_shell/': typeof ShellIndexRoute
  '/_shell/feeds/$feedId': typeof ShellFeedsFeedIdRoute
  '/_shell/folders/$folderId': typeof ShellFoldersFolderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/saved'
    | '/settings'
    | '/feeds/$feedId'
    | '/folders/$folderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/saved'
    | '/settings'
    | '/'
    | '/feeds/$feedId'
    | '/folders/$folderId'
  id:
    | '__root__'
    | '/_shell'
    | '/login'
    | '/_shell/saved'
    | '/_shell/settings'
    | '/_shell/'
    | '/_shell/feeds/$feedId'
    | '/_shell/folders/$folderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings': {
      id: '/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/saved': {
      id: '/_shell/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof ShellSavedRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/folders/$folderId': {
      id: '/_shell/folders/$folderId'
      path: '/folders/$folderId'
      fullPath: '/folders/$folderId'
      preLoaderRoute: typeof ShellFoldersFolderIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/feeds/$feedId': {
      id: '/_shell/feeds/$feedId'
      path: '/feeds/$feedId'
      fullPath: '/feeds/$feedId'
      preLoaderRoute: typeof ShellFeedsFeedIdRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellSavedRoute: typeof ShellSavedRoute
  ShellSettingsRoute: typeof ShellSettingsRoute
  ShellIndexRoute: typeof ShellIndexRoute
  ShellFeedsFeedIdRoute: typeof ShellFeedsFeedIdRoute
  ShellFoldersFolderIdRoute: typeof ShellFoldersFolderIdRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellSavedRoute: ShellSavedRoute,
  ShellSettingsRoute: ShellSettingsRoute,
  ShellIndexRoute: ShellIndexRoute,
  ShellFeedsFeedIdRoute: ShellFeedsFeedIdRoute,
  ShellFoldersFolderIdRoute: ShellFoldersFolderIdRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
